name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { ruby: 3.1, allowed-failure: false }
          - { ruby: 3.4, allowed-failure: false }
          - { ruby: ruby-head, allowed-failure: true }
    name: Test Ruby ${{ matrix.entry.ruby }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{ matrix.entry.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
        continue-on-error: ${{ matrix.entry.allowed-failure }}
